SELECT SYS_GUID(), UID, USER FROM DUAL
UNION ALL
SELECT SYS_GUID(), UID, USER FROM DUAL
UNION ALL   
SELECT SYS_GUID(), UID, USER FROM DUAL;

SELECT ROWID AS XX, ROWNUM FROM EMP;

SELECT SYS_CONTEXT ('USERENV', 'SESSION_USER')  FROM DUAL;   
   
SELECT SYS_CONTEXT ('USERENV', 'TERMINAL') FROM DUAL;      

SELECT SYS_CONTEXT ('USERENV', 'HOST') FROM DUAL;     

SELECT SYS_CONTEXT ('USERENV', 'OS_USER') FROM DUAL;    